Update Doc and README
lifescapegame/bevy_replicon pull request #40
Opened 2023-09-20 13:46 UTC by PitiBouchon

Trying to be a bit more user friendly for beginners

2023-09-20 19:03 UTC, Shatur requested changes
Thanks! A couple suggestions:

2023-09-20 19:03 UTC, Shatur commented on README.md
> +You can try out the [examples](https://github.com/lifescapegame/bevy_replicon/tree/master/examples) with `cargo run --example tic_tac_toe`
I would simplify it:
```suggestion
See also [Tic-Tac-Toe](https://github.com/lifescapegame/bevy_replicon/tree/master/examples/tic_tac_toe.rs) example.
```

2023-09-20 19:34 UTC, PitiBouchon reviewed
Improved naming and readability

2023-09-22 09:09 UTC, Shatur approved these changes

2023-09-22 09:09 UTC, merged